"""Notion block trees -> plain text, links, and child references.

Pure functions only: no I/O, no clock, no randomness. The fetcher builds the
tree, this module renders it, and replay re-runs this over stored payloads and
must reproduce the same body byte for byte.

A Notion page has no body field. Its content is a tree of blocks reached through
/v1/blocks/{id}/children, so "the body" is something we construct — and how we
construct it is a retrieval decision, not a formatting one. The output is
markdown-ish because chunking and embedding both do better with structure
retained than with a wall of concatenated spans.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from connectors.notion.models import Block, RichText, notion_entity_id, plain

# Blocks whose text is pure navigation chrome, generated by Notion rather than
# written by anyone. Rendering them fills bodies with duplicate headings.
SKIP_TYPES: frozenset[str] = frozenset(
    {"table_of_contents", "breadcrumb", "divider", "unsupported"}
)

HEADING_PREFIX: dict[str, str] = {
    "heading_1": "# ",
    "heading_2": "## ",
    "heading_3": "### ",
}


@dataclass(frozen=True)
class LinkTarget:
    """A link found in a body.

    `entity_id` is set for in-Notion mentions, already namespaced — the API
    hands us the target id directly and no URL parsing is needed. `url` is set
    for everything else (including Slack and Drive permalinks). The generator
    resolves those against live nodes of other types and mints `mentions`
    edges; unresolved ones stay on the page payload as `link_urls`.
    """

    url: str | None = None
    entity_id: str | None = None
    label: str | None = None
    relation: str = "mentions"


@dataclass
class BlockNode:
    """One block plus its fetched children."""

    block: Block
    children: list[BlockNode] = field(default_factory=list)


def render(tree: list[BlockNode]) -> str:
    """The page body as text."""
    lines: list[str] = []
    _render_into(tree, lines, depth=0)
    # Collapse the runs of blank lines that nested empty blocks produce.
    out: list[str] = []
    for line in lines:
        if line.strip() or (out and out[-1].strip()):
            out.append(line)
    return "\n".join(out).strip()


def links(tree: list[BlockNode]) -> list[LinkTarget]:
    """Every outbound link, de-duplicated, in document order."""
    found: dict[str, LinkTarget] = {}
    for node in _walk(tree):
        block = node.block
        for target in _rich_text_links(block.rich_text):
            found.setdefault(_key(target), target)
        # Bookmarks and embeds carry their URL outside rich_text.
        if block.type in {"bookmark", "embed", "link_preview"}:
            url = block.content.get("url")
            if url:
                found.setdefault(f"url:{url}", LinkTarget(url=url))
        # A link_to_page block is a pointer, not containment: it renders as a
        # link and must not confer access.
        if block.type == "link_to_page":
            content = block.content
            target_id = content.get("page_id") or content.get("database_id")
            if target_id:
                found.setdefault(
                    f"id:{target_id}",
                    LinkTarget(
                        entity_id=notion_entity_id(target_id), relation="links to"
                    ),
                )
    return list(found.values())


def child_page_ids(tree: list[BlockNode]) -> list[str]:
    """Sub-pages, which are their own nodes and inherit access by containment.

    Deliberately separate from links(): a child_page is structural, a mention of
    the same page is not, and conflating them would make a mention confer access.
    """
    return [n.block.id for n in _walk(tree) if n.block.type == "child_page"]


def child_database_ids(tree: list[BlockNode]) -> list[str]:
    return [n.block.id for n in _walk(tree) if n.block.type == "child_database"]


# --------------------------------------------------------------- internals --


def _walk(tree: list[BlockNode]):
    for node in tree:
        yield node
        yield from _walk(node.children)


def _key(target: LinkTarget) -> str:
    return f"id:{target.entity_id}" if target.entity_id else f"url:{target.url}"


def _rich_text_links(spans: list[RichText]) -> list[LinkTarget]:
    out: list[LinkTarget] = []
    for span in spans:
        mention = span.mention or {}
        kind = mention.get("type")
        # Page and database mentions hand us the id directly — no URL parsing,
        # no ambiguity about which workspace the link points at.
        if kind in {"page", "database", "data_source"}:
            target = mention.get(kind) or {}
            if target.get("id"):
                out.append(
                    LinkTarget(
                        entity_id=notion_entity_id(target["id"]),
                        label=span.plain_text or None,
                    )
                )
                continue
        if span.href:
            out.append(LinkTarget(url=span.href, label=span.plain_text or None))
    return out


def _render_into(tree: list[BlockNode], lines: list[str], *, depth: int) -> None:
    indent = "  " * depth
    numbered = 0
    for node in tree:
        block, content = node.block, node.block.content
        btype = block.type

        if block.trashed or btype in SKIP_TYPES:
            continue

        numbered = numbered + 1 if btype == "numbered_list_item" else 0
        text = plain(block.rich_text)

        if btype in HEADING_PREFIX:
            lines.append("")
            lines.append(f"{HEADING_PREFIX[btype]}{text}")
        elif btype == "bulleted_list_item":
            lines.append(f"{indent}- {text}")
        elif btype == "numbered_list_item":
            lines.append(f"{indent}{numbered}. {text}")
        elif btype == "to_do":
            box = "x" if content.get("checked") else " "
            lines.append(f"{indent}- [{box}] {text}")
        elif btype == "quote":
            lines.append(f"{indent}> {text}")
        elif btype == "callout":
            lines.append(f"{indent}{text}")
        elif btype == "code":
            language = content.get("language") or ""
            lines.extend([f"```{language}", text, "```"])
        elif btype == "equation":
            lines.append(content.get("expression", ""))
        elif btype == "child_page":
            # Rendered as a reference only. Its content belongs to its own node,
            # and duplicating it here would double-count in retrieval.
            lines.append(f"{indent}[page] {content.get('title', '')}")
        elif btype == "child_database":
            lines.append(f"{indent}[database] {content.get('title', '')}")
        elif btype == "table_row":
            cells = content.get("cells", []) or []
            rendered = [
                plain([RichText.model_validate(s) for s in cell]) for cell in cells
            ]
            lines.append(f"{indent}| " + " | ".join(rendered) + " |")
        elif btype in {"image", "file", "pdf", "video", "audio"}:
            # Never the URL: Notion's file URLs expire in about an hour, so a
            # stored one is a broken link by the time anyone retrieves it. The
            # block id in the payload is the durable reference.
            caption = plain(
                [RichText.model_validate(s) for s in content.get("caption", [])]
            )
            name = content.get("name") or caption or btype
            lines.append(f"{indent}[{btype}] {name}")
        elif btype in {"bookmark", "embed", "link_preview"}:
            url = content.get("url", "")
            lines.append(f"{indent}{url}" if url else "")
        elif text:
            # paragraph, toggle, synced_block, column, and anything Notion adds
            # later that follows the rich_text convention.
            lines.append(f"{indent}{text}" if depth else text)

        if node.children:
            # Table rows and columns are layout, not nesting: indenting their
            # children would misrepresent the document structure.
            child_depth = depth if btype in {"column_list", "column", "table"} else depth + 1
            _render_into(node.children, lines, depth=child_depth)
